// Interface automatically generated by schemas-to-ts

import { Location } from '../components/shared/Location';
import { Contact } from '../components/shared/Contact';
import { Location_Plain } from '../components/shared/Location';
import { Contact_Plain } from '../components/shared/Contact';
import { Location_NoRelations } from '../components/shared/Location';
import { Contact_NoRelations } from '../components/shared/Contact';

export interface Agency {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    agencyLicense?: string;
    location?: Location;
    contact?: Contact;
  };
}
export interface Agency_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  agencyLicense?: string;
  location?: Location_Plain;
  contact?: Contact_Plain;
}

export interface Agency_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  agencyLicense?: string;
  location?: Location_NoRelations;
  contact?: Contact_NoRelations;
}

export interface Agency_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  agencyLicense?: string;
  location?: Location_Plain;
  contact?: Contact_Plain;
}
