// Interface automatically generated by schemas-to-ts

import { Agency } from './agency';
import { Location } from '../components/shared/Location';
import { Contact } from '../components/shared/Contact';
import { Agency_Plain } from './agency';
import { Location_Plain } from '../components/shared/Location';
import { Contact_Plain } from '../components/shared/Contact';
import { Location_NoRelations } from '../components/shared/Location';
import { Contact_NoRelations } from '../components/shared/Contact';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Agent {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    agentLicenseNumber?: string;
    firstName?: string;
    lastName?: string;
    agency?: { data: Agency };
    location?: Location;
    contact?: Contact;
  };
}
export interface Agent_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  agentLicenseNumber?: string;
  firstName?: string;
  lastName?: string;
  agency?: Agency_Plain;
  location?: Location_Plain;
  contact?: Contact_Plain;
}

export interface Agent_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  agentLicenseNumber?: string;
  firstName?: string;
  lastName?: string;
  agency?: number;
  location?: Location_NoRelations;
  contact?: Contact_NoRelations;
}

export interface Agent_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  agentLicenseNumber?: string;
  firstName?: string;
  lastName?: string;
  agency?: AdminPanelRelationPropertyModification<Agency_Plain>;
  location?: Location_Plain;
  contact?: Contact_Plain;
}
