// Interface automatically generated by schemas-to-ts

import { Media } from '../components/shared/Media';
import { Author } from './author';
import { Category } from './category';
import { Media_Plain } from '../components/shared/Media';
import { Author_Plain } from './author';
import { Category_Plain } from './category';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    slug?: string;
    cover?: { data: Media };
    author?: { data: Author };
    category?: { data: Category };
    blocks?: any;
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: Media_Plain;
  author?: Author_Plain;
  category?: Category_Plain;
  blocks?: any;
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: number;
  author?: number;
  category?: number;
  blocks?: any;
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  author?: AdminPanelRelationPropertyModification<Author_Plain>;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  blocks?: any;
}
