// Interface automatically generated by schemas-to-ts

import { Media } from '../components/shared/Media';
import { Article } from './article';
import { Media_Plain } from '../components/shared/Media';
import { Article_Plain } from './article';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Author {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    avatar?: { data: Media };
    email?: string;
    articles: { data: Article[] };
  };
}
export interface Author_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  avatar?: Media_Plain;
  email?: string;
  articles: Article_Plain[];
}

export interface Author_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  avatar?: number;
  email?: string;
  articles: number[];
}

export interface Author_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  avatar?: AdminPanelRelationPropertyModification<Media_Plain>;
  email?: string;
  articles: AdminPanelRelationPropertyModification<Article_Plain>;
}
