// Interface automatically generated by schemas-to-ts

import { Media } from '../components/shared/Media';
import { Seo } from '../components/shared/Seo';
import { Media_Plain } from '../components/shared/Media';
import { Seo_Plain } from '../components/shared/Seo';
import { Seo_NoRelations } from '../components/shared/Seo';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Global {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    siteName: string;
    favicon?: { data: Media };
    siteDescription: string;
    defaultSeo?: Seo;
  };
}
export interface Global_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  siteName: string;
  favicon?: Media_Plain;
  siteDescription: string;
  defaultSeo?: Seo_Plain;
}

export interface Global_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  siteName: string;
  favicon?: number;
  siteDescription: string;
  defaultSeo?: Seo_NoRelations;
}

export interface Global_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  siteName: string;
  favicon?: AdminPanelRelationPropertyModification<Media_Plain>;
  siteDescription: string;
  defaultSeo?: Seo_Plain;
}
