// Interface automatically generated by schemas-to-ts

export interface Building {
  livingArea?: number;
  newConstruction?: boolean;
  bungalow?: boolean;
  splitLevel?: boolean;
  semiDetached?: boolean;
  century?: boolean;
  detached?: boolean;
  attached?: boolean;
  buildYear?: number;
}
export interface Building_Plain {
  livingArea?: number;
  newConstruction?: boolean;
  bungalow?: boolean;
  splitLevel?: boolean;
  semiDetached?: boolean;
  century?: boolean;
  detached?: boolean;
  attached?: boolean;
  buildYear?: number;
}

export interface Building_NoRelations {
  livingArea?: number;
  newConstruction?: boolean;
  bungalow?: boolean;
  splitLevel?: boolean;
  semiDetached?: boolean;
  century?: boolean;
  detached?: boolean;
  attached?: boolean;
  buildYear?: number;
}

