// Interface automatically generated by schemas-to-ts

export interface Contact {
  primaryPhone?: string;
  email?: string;
  website?: string;
}
export interface Contact_Plain {
  primaryPhone?: string;
  email?: string;
  website?: string;
}

export interface Contact_NoRelations {
  primaryPhone?: string;
  email?: string;
  website?: string;
}

