// Interface automatically generated by schemas-to-ts

import { Contact } from './Contact';
import { Location } from './Location';
import { Agency } from '../../api/agency';
import { Contact_Plain } from './Contact';
import { Location_Plain } from './Location';
import { Agency_Plain } from '../../api/agency';
import { Contact_NoRelations } from './Contact';
import { Location_NoRelations } from './Location';

export interface Entity {
  name?: string;
  contact?: Contact;
  location?: Location;
  agency?: { data: Agency };
}
export interface Entity_Plain {
  name?: string;
  contact?: Contact_Plain;
  location?: Location_Plain;
  agency?: Agency_Plain;
}

export interface Entity_NoRelations {
  name?: string;
  contact?: Contact_NoRelations;
  location?: Location_NoRelations;
  agency?: number;
}

