// Interface automatically generated by schemas-to-ts

export interface Features {
  bedrooms?: number;
  bathrooms?: number;
  parking?: number;
  garages?: number;
  pool?: boolean;
  reducedMobility?: boolean;
  waterfront?: boolean;
  smokingAllowed?: boolean;
  elevator?: boolean;
  waterAccess?: boolean;
  petsAllowed?: boolean;
}
export interface Features_Plain {
  bedrooms?: number;
  bathrooms?: number;
  parking?: number;
  garages?: number;
  pool?: boolean;
  reducedMobility?: boolean;
  waterfront?: boolean;
  smokingAllowed?: boolean;
  elevator?: boolean;
  waterAccess?: boolean;
  petsAllowed?: boolean;
}

export interface Features_NoRelations {
  bedrooms?: number;
  bathrooms?: number;
  parking?: number;
  garages?: number;
  pool?: boolean;
  reducedMobility?: boolean;
  waterfront?: boolean;
  smokingAllowed?: boolean;
  elevator?: boolean;
  waterAccess?: boolean;
  petsAllowed?: boolean;
}

