// Interface automatically generated by schemas-to-ts

export interface Location {
  street?: string;
  state?: string;
  country?: string;
  codePostal?: string;
  lat?: string;
  long?: string;
  civicName?: string;
  address?: string;
  city?: string;
  neighborhood?: string;
  borough?: string;
}
export interface Location_Plain {
  street?: string;
  state?: string;
  country?: string;
  codePostal?: string;
  lat?: string;
  long?: string;
  civicName?: string;
  address?: string;
  city?: string;
  neighborhood?: string;
  borough?: string;
}

export interface Location_NoRelations {
  street?: string;
  state?: string;
  country?: string;
  codePostal?: string;
  lat?: string;
  long?: string;
  civicName?: string;
  address?: string;
  city?: string;
  neighborhood?: string;
  borough?: string;
}

