// Interface automatically generated by schemas-to-ts

export interface PropertyCharacteristics {
  rooms?: number;
  sqMts?: number;
  bathrooms?: number;
  elevator?: boolean;
  pool?: boolean;
  vigilanceSystem?: boolean;
  indoorParking?: number;
  outdoorParking?: number;
  reducedMobility?: boolean;
  waterFront?: boolean;
  waterAccess?: boolean;
  petsFriendly?: boolean;
}
export interface PropertyCharacteristics_Plain {
  rooms?: number;
  sqMts?: number;
  bathrooms?: number;
  elevator?: boolean;
  pool?: boolean;
  vigilanceSystem?: boolean;
  indoorParking?: number;
  outdoorParking?: number;
  reducedMobility?: boolean;
  waterFront?: boolean;
  waterAccess?: boolean;
  petsFriendly?: boolean;
}

export interface PropertyCharacteristics_NoRelations {
  rooms?: number;
  sqMts?: number;
  bathrooms?: number;
  elevator?: boolean;
  pool?: boolean;
  vigilanceSystem?: boolean;
  indoorParking?: number;
  outdoorParking?: number;
  reducedMobility?: boolean;
  waterFront?: boolean;
  waterAccess?: boolean;
  petsFriendly?: boolean;
}

